### ISSUE TITLE
Add PWA offline support

### ISSUE THREAD

**Issue by crutchcorn** [jacksonhvisuals/5217-web#28]
Currently, there is no service worker that is registered, does not respond with 200 when offline and cannot install the app offline. It would be ideal to add service worker support for this so that the user can use the webapp when offline.

I'll likely make a PR to make this happen later either next week or this week

**Comment by jacksonhvisuals** [comment]
oh sweet!

**Comment by myfrom** [comment]
Hi!
Can I ask if you are still working on this, @crutchcorn ? If not, could I take it? I have some free time and would really like to see this as a fully-featured PWA.
I could also look for possibilities on getting this to Microsoft Store as they announced PWA support some time ago.

**Comment by crutchcorn** [comment]
@myfrom I am not, actually. :sweat_smile: I would if I had time but ran out. Let me know if there's anything I can do to help!

**Comment by jacksonhvisuals** [comment]
You're 100% awesome, @myfrom!

**Comment by myfrom** [comment]
Thank you 😄 

I currently have the Service Worker ready and I'm going through some last touches/documenting it and further optimising. I'm gonna have a PR ready by Tuesday.

I decided to go with [Workbox](https://developers.google.com/web/tools/workbox/) because I'm quite familiar with it, it has a very simple and straight-forward configuration and even tho it adds one step before publishing it takes care of all sorts of things from revisioning to cross-site requests so I think it's worth that one command. I'll document all the required things in readme before I submit a PR.

Oh, and one more question - do you have a 512px icon? Chrome might reject to show add-to-home-screen prompt if it's not provided 😕

**Comment by jacksonhvisuals** [comment]
Fantastic. I don't have a 512px icon, but I think @franciscofranco will.

**Comment by franciscofranco** [comment]
I'll make a PR with the 512px icon sometime tonight.

**Comment by jacksonhvisuals** [comment]
Sweet, thanks!

**Comment by myfrom** [comment]
I think it can be closed now, after #33 was merged

**Comment by jacksonhvisuals** [comment]
Did we get a 512px icon from @franciscofranco? I can't find it...

**Comment by jacksonhvisuals** [comment]
Let's go ahead and add it, and if/when (lol) @franciscofranco can send us the 512px one, we'll just update it. @myfrom 

By the way, Francisco told me that he is crazy busy with some personal stuff, so I don't really want to pressure him right now and add to his already-full plate.

**Comment by myfrom** [comment]
Done 😊 We should now start seeing the 'install app' banners

**Comment by franciscofranco** [comment]
Pushed the real icon.
