### ISSUE TITLE
Server gives 404 for icon font files even tho they exist

### ISSUE THREAD

**Issue by gabrc52** [jacksonhvisuals/5217-web#46]
Icons don't appear properly as a 404 is thrown trying to load the following files:

https://web.5217.app/node_modules/material-design-icons/iconfont/MaterialIcons-Regular.ttf
https://web.5217.app/node_modules/material-design-icons/iconfont/MaterialIcons-Regular.woff
https://web.5217.app/node_modules/material-design-icons/iconfont/MaterialIcons-Regular.woff2

**Comment by myfrom** [comment]
Thanks for the report!

I have also noticed that but I thought it's caching issue on my end because it's a very weird bug: **the files are on deployed gh-pages branch** and I also haven't found any typos or mistakes in path ([link](https://github.com/jacksonhvisuals/5217-web/tree/gh-pages/node_modules/material-design-icons/iconfont)). I'm afraid it's something related to Github Pages, on which the webapp is hosted. I am looking into it and trying to find possible solutions or workarounds.

**Comment by myfrom** [comment]
Same issue on my fork, so it seems like the custom domain isn't related to the problem

**Comment by myfrom** [comment]
I think I've found a workaround.

I'd be grateful if someone could go to https://myfrom.github.io/5217-web/ and verify that icons are loading

**Comment by gabrc52** [comment]
Yes, they are loading
